# Generated by Django 3.1.1 on 2020-10-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Covers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('cover_title', models.CharField(max_length=100)),
                ('cover_artist', models.CharField(max_length=100)),
                ('cover_song', models.CharField(max_length=100)),
                ('audio', models.BinaryField()),
            ],
        ),
    ]
