# Generated by Django 3.1.1 on 2020-10-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_covers_cover_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covers',
            name='audio',
        ),
        migrations.AddField(
            model_name='covers',
            name='audio_url',
            field=models.CharField(default='', max_length=150),
        ),
    ]
